<html>
    <head>
        <?php include 'views/inc/head.phtml'; ?>
        <title><?= $titulo; ?></title>
    </head>
    <body>
        <div id='contenedor'>
            <?php include 'views/inc/cabecera.phtml'; ?>


                <div class="modal fade" id="borrarObra" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
                    <div class="modal-dialog modal-lg" role="document">

                        Content
                        <div class="modal-content">


                            <div class="modal-body">
                                <h4>Baja de obra</h4>
                                <hr />
                                <div class="form-group row">                       
                                    <div class="col-sm-4">
                                        <strong>Nombre</strong>
                                    </div>
                                    <div class="col-sm-8">
                                        <?= $o[1] ?>
                                    </div>
                                </div>
                                <div class="form-group row">                       
                                    <div class="col-sm-4">
                                        <strong>Dirección</strong>
                                    </div>
                                    <div class="col-sm-8">
                                        <?= $o[2] ?>
                                    </div>
                                </div>
                                <div class="form-group row">                       
                                    <div class="col-sm-4">
                                        <strong>CP / Población</strong>
                                    </div>
                                    <div class="col-sm-8">
                                        <?= $o[3] ?> / <?= $o[4] ?> 
                                    </div>
                                </div>
                                <div class="row">
                                    <hr />
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                    <a href="obra.php?id=<?= $id; ?>&action=confirmdelete" class="btn btn-danger btn-sm  ">
                                        <i class="fas fa-trash-alt" ></i> Confirmar baja
                                    </a>
                                    </div>
                                    <div class='col-sm-6 text-right'>
                                    <a href="<?= @$_SERVER[HTTP_REFERER]; ?>" class="btn btn-secondary btn-sm"><i class='fas fa-times-circle ' ></i>&nbsp;Cancelar</a>
                                 </div>
                                </div>

                            </div>



                        </div>

                    </div>
                </div>


            <?php include 'views/inc/pie.phtml'; ?>
        </div>
        <script>
                $('#borrarObra').modal('show');
            </script>

    </body>
</html>
